# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('author', models.TextField()),
                ('date', models.DateTimeField()),
                ('description', models.DateTimeField()),
            ],
        ),
    ]
