# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='commit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commits.Repository'),
            preserve_default=False,
        ),
    ]
