# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_auto_20170721_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='id',
        ),
        migrations.AlterField(
            model_name='commit',
            name='identifier',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
