# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0003_auto_20170722_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='id',
        ),
        migrations.AddField(
            model_name='commit',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='identifier',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
