# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0004_auto_20170722_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='parents',
            field=models.TextField(default='Dunno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.TextField(),
        ),
    ]
